### ISSUE TITLE
Issues with a cheap microSDHC cards

### ISSUE THREAD

**Issue by Sgw32** [arananet/Tapuino-Reloaded#11]
Hi, 

First of all - thanks for the project. 
I think I would better open an issue on tapuino repo, but it is outdated for sure. 

Anyway - that's the problem. I have a lot of microSD HC cards for 8-16-32 Gb from Ali and they are working fine on tapecart and patched SD2IEC by me but here it just says "Init Failed v 2.8.0". I've checked code and there is no direct SDHC support(it should send 0xFF for several times, then send a special payload, then proceed to fatfs - that's required for SDHC) , so I think - most of cards are just unsupported, that's a big issue as I think. I have 2 tapuino units and I've checked all parts, but I continue checking if anything is wrong. Anyway there are no solder bridges or something else, everything is just fine, but still does not work. 
Which cards are supported, which cards do anyone use? 

I unfortunately do not have microSD(not HC/XC!) cards so I can't test it on microSD, however, in most cases microSD support means microSDHC support too - but not works here.

Best regards,
Fedor.

**Comment by arananet** [comment]
Hi, that's firmware related, not hardware related. Anyway, I've used standard microsd from 4,8,16,32GB of any brand and they all work. I just format on FAT32 and that's all.

Tapuino Reloaded uses the Tapuino Firmware from Peter Edwards.

Anyway, a user has detected a problem that might ocurrs if pcb fabrication does not populate the via required on pin 8 of the buffer hc4050. Check fix at https://github.com/arananet/Tapuino-Reloaded/tree/master/gerbers-nano

**Comment by Sgw32** [comment]
Already connected this pin, however still no progress.
Are your cards SDHC and not SD?

Ill buy a couple of microSD(not HC) cards next week and write if it will work. 

Thanks!

**Comment by arananet** [comment]
SD >=8GB are SDHC. They also work.

Another thing that can produce a problem is the current Nano version that you have chosen on the Arduino Ide, you must choose (if it appears as an option), Nano Old boot loader.

**Comment by Sgw32** [comment]
https://raw.githubusercontent.com/arananet/Tapuino-Reloaded/master/images/TapuinoReloadedreal.jpg

Nano old bootloader selected, firmware is loaded and screen is working. However, look at repo image - it also says init failed. Card inserted. 
I do not know issues with FatFS, it works good with SDHC even with a version from 2009(Tested!) however there is no SDHC payload in the code. Such payload is not required as I know on good cards i.e. transcend, sandisk and some others, while ALYNX and other noname brands may require it.. Anyway I fixed such a problem with deleting a reply waiting from sd card, so most of cards just do not answer at detect stage, but still work. I also mean, it should work with all known types of FAT. My cards are however FAT32 with standard partitition.

**Comment by arananet** [comment]
I see.

If the problem is related to the partition and not the SD CARD itself, then you can use DISKPART from WINDOWS to make a 2GB partition on the SD and format it to fat32. This works on some retro hardware projects as a "fix".

**Comment by Sgw32** [comment]
Thanks. I'll check it today or tomorrow.

**Comment by Sgw32** [comment]
Hi. Issue solved - Arduino Nano clones from China have a weak 3V3 regulator. It is needed to add an external one to 3V3 pin(from 5V) AMS/LM1117-3V3 is working. 
I recommend you to release the schematic (probably PCB too ... if possible 😃 ) I spent some time probing signals after importing gerbers to Sprint Layout... Your board is a bit different because uses 4050 as a voltage converter instead of voltage dividers/direct driving. 

Anyway thanks! :D

**Comment by arananet** [comment]
Hi, thanks for the update. Well, that's not entirely a tapuino reloaded nor firmware issue, instead, of the NANO that you are using. On the version that I've on sale on my store, I put the atmega directly on the PCB and a 3v3 regulator to power all the 3v3 signals. Sometimes when a AMS1117-3v3 is used, you just need to add a 22UF capacitor to the 3v3 output to fix the lower output. It is stated on the AMS1117-3v3 datasheet :)

"The  addition  of 22μF  solid  tantalum  on  the  output  will  ensure  stability for all operating conditions."

Thanks for your time.
