### ISSUE TITLE
Tapuino 0.2 Replacement for 2n2222

### ISSUE THREAD

**Issue by sajattack** [arananet/Tapuino-Reloaded#5]
So I guess the 2n2222 was discontinued or something and prices skyrocketed. I have the 0.2 design which looks like still needs it? Can I replace it with another sot-23 transistor? What would you recommend?

**Comment by sajattack** [comment]
How's this? https://www.digikey.ca/product-detail/en/diodes-incorporated/MMBT2222A-7-F/MMBT2222A-FDICT-ND/815723

**Comment by arananet** [comment]
2n2222 is not discontinued but I just not necessary on new designs. That part will work
