### ISSUE TITLE
No Inicializado Error

### ISSUE THREAD

**Issue by sajattack** [arananet/Tapuino-Reloaded#6]
I'm testing my Tapuino Reloaded v0.2, just by powering it from an arduino, and it says "No Inicializado", with or without an sd card. Is there something special that needs to go on the sd card?

**Comment by sajattack** [comment]
Oh, probably the transistors I forgot about.

**Comment by arananet** [comment]
It needs to be formatted on fat32 at least.

**Comment by sajattack** [comment]
I have one 16GB fat32-formatted micro-sd card and two tapuinos. One of the tapuinos says "No Inicializado" as I mentioned, and the other one just gets stuck on "Inicializando" Do I need like a .lst file or anything on the sd card? Does it support folders?

**Comment by arananet** [comment]
Tapuino works with fat partition. So you don't need any special file. If you get stuck on initialization, it's a hw problem. When the code send a the initialization chain to the SD, this return status and start with the reading. If it get stucked then something keeps from doing that. Check soldering on sd socket. Check continuity on the miso mosi sck pins between the SD and the arduino. I don't know what else you your check. Tapuino 0.2 was one of the first protos.

**Comment by sajattack** [comment]
Does the RXD TXD header have debug info? Also, I bought 74hc4050, I notice in another issue you recommend 74hc**t**4050, could that be a problem?

**Comment by sajattack** [comment]
I got one of them working by reprogramming it, and started making comparisons between the working and non-working version. The best clue I got was that "diode drop" on my multimeter between vcc and gnd was 1.5-ish volts on the working one and 1.9ish on the non-working one. Something shorted and drawing too much power? idk.

**Comment by arananet** [comment]
Yes that can be. A short or a bad arduino module too. You can debug the arduino via serial on the arduino ide. Connecting the tx and rx using a usb to ttl adapter.

**Comment by sajattack** [comment]
baudrate?

**Comment by sajattack** [comment]
I couldn't get anything more than echoback out of it, even on the working one, I see on https://github.com/sweetlilmre/tapuino it might be 57600, but even then the serial is behind an ifdef which may or not be defined, and even if it is defined, I see no calls to serial_println.

**Comment by arananet** [comment]
This is basic arduino debug you need to research yourself.
