### ISSUE TITLE
Init Failed ! v:2.8.0

### ISSUE THREAD

**Issue by SnobolPL1** [arananet/Tapuino-Reloaded#7]
Having recieved my TAPUINO Reloaded v0.41 it's saying " Init Failed !" Please help Many Thanks

**Comment by arananet** [comment]
> Having recieved my TAPUINO Reloaded v0.41 it's saying " Init Failed !" Please help Many Thanks

hi. Where did you buy it? this web is not for this. If you got any problem and you buy from arananet.net please contact to info@arananet.net and provide the order number. thanks.
