### ISSUE TITLE
v0.41 display

### ISSUE THREAD

**Issue by chuckcaley** [arananet/Tapuino-Reloaded#8]
I have made one of these boards but i am having a problem with the display.
My display has the letters of GND VCC SCL SDA. But when i connect it to the board i just get some random dots on 4 lines. If i put in my 128x64 display that reads ok  The letters on that are GND VCC SCK SDA. What do i need to do to get the display with SCL working as that is a 128x32 display?

**Comment by arananet** [comment]
This is not an issue... displays with SCK and SDA requires pullups with a 4k7 resistors in order to work. The correct display will be those that has the SCL SDA.
